# ------------------- Give a name to the new test run --------------------

namethetest: 'tere_news_telegraaf'

# ------------------- General input variables --------------------

inputs:
  directory: '/data/groups/trifecta/teresa/CHR/Exp_Diac/tests/test_data/'

# ------------------- Preprocessing settings --------------------

preprocessing:
  skip: True
  savepreprocessed: True
  pipelines:
    minwordlength: 3
    lowercase: True
    remove_punctuation: True
    remove_stopwords: True


# ------------------- Training settings --------------------

training:
  skip: False
  options:
    epochs: 3
    vector_size: 300
    sg: True
    min_count: 5
    window: 3
    start_alpha: 0.025
    end_alpha: 0.025
    workers: 10

# ------------------- Alignment settings --------------------
alignment:
  skip: False
